// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbDSRtUUxhmfW9lKJRtTy1-kCozDrBcaY',
    appId: '1:136215951997:web:41c51a9f6482b62541cf14',
    messagingSenderId: '136215951997',
    projectId: 'job-vibe-ce3e6',
    authDomain: 'job-vibe-ce3e6.firebaseapp.com',
    storageBucket: 'job-vibe-ce3e6.firebasestorage.app',
    measurementId: 'G-ZNVB0G1TVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRp1UHcl6LsGeM3ocJ0eNZ8iTiUId9Bfw',
    appId: '1:136215951997:android:80a7aac6b62f878341cf14',
    messagingSenderId: '136215951997',
    projectId: 'job-vibe-ce3e6',
    storageBucket: 'job-vibe-ce3e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZQOLJf5W8VQ2xHiNI4FUGIyidHoa-SAU',
    appId: '1:136215951997:ios:e89c3fb602c6763141cf14',
    messagingSenderId: '136215951997',
    projectId: 'job-vibe-ce3e6',
    storageBucket: 'job-vibe-ce3e6.firebasestorage.app',
    iosBundleId: 'com.happnj.jobSwipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZQOLJf5W8VQ2xHiNI4FUGIyidHoa-SAU',
    appId: '1:136215951997:ios:e89c3fb602c6763141cf14',
    messagingSenderId: '136215951997',
    projectId: 'job-vibe-ce3e6',
    storageBucket: 'job-vibe-ce3e6.firebasestorage.app',
    iosBundleId: 'com.happnj.jobSwipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbDSRtUUxhmfW9lKJRtTy1-kCozDrBcaY',
    appId: '1:136215951997:web:de0eee355f8a710741cf14',
    messagingSenderId: '136215951997',
    projectId: 'job-vibe-ce3e6',
    authDomain: 'job-vibe-ce3e6.firebaseapp.com',
    storageBucket: 'job-vibe-ce3e6.firebasestorage.app',
    measurementId: 'G-R3JJJH2X64',
  );
}
